auth/urls.py
from django.urls import path, include
from .views import reset_password
urlpatterns = [
    path('password/change/done/', reset_password),
    path('', include('registration.backends.default.urls'))
]

blog/urls.py
from django.urls import path
from .views import BlogListView, BlogDetailView, BlogCommentView

app_name = 'blogs'

urlpatterns = [
    path('<int:pk>/comment/', BlogCommentView.as_view(), name='blog_comment'),
    path('<int:pk>/post/', BlogDetailView.as_view(), name='blog_detail'),
    path('', BlogListView.as_view(), name='blog_list')
]

config/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

]

urlpatterns += i18n_patterns(
    path('accounts/', include('auth.urls')),
    path('admin/', admin.site.urls),
    path('order/', include('orders.urls', namespace='orders')),
    path('profile/', include('client.urls', namespace='profile')),
    path('product/', include('product.urls', namespace='products')),
    path('shop/', include('shop.urls', namespace='shops')),
    path('blog/', include('blog.urls', namespace='blogs')),
    path('', include('pages.urls', namespace='pages'))
)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path

from orders.views import CheckoutView, OrderHistoryListView

app_name = 'orders'

urlpatterns = [
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('history/', OrderHistoryListView.as_view(), name='history')
]

pages/urls.py
from django.urls import path
from .views import HomePageView, ContactView, AboutView

app_name = 'pages'

urlpatterns = [
    path('about/', AboutView.as_view(), name='about'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('', HomePageView.as_view(), name='home')
]

product/urls.py
from django.urls import path
from .views import update_wishlist, WishlistView, update_cart, CartListView

app_name = 'products'

urlpatterns = [
    path('wishlist/', WishlistView.as_view(), name='wishlist'),
    path('<int:pk>/wishlist/', update_wishlist, name='add_wishlist'),
    path('<int:pk>/cart/', update_cart, name='add_cart'),
    path('shopping/cart/', CartListView.as_view(), name='shopping_cart')
]

shop/urls.py
from django.urls import path
from .views import ShopView, ProductDetailView

app_name = 'shops'

urlpatterns = [
    path('', ShopView.as_view(), name='shop'),
    path('<int:pk>/detail/', ProductDetailView.as_view(), name='product_detail'),
]

shop/models.py
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _


class ColorModel(models.Model):
    code = models.CharField(max_length=7, verbose_name=_("code"))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_("created at"))

    def __str__(self):
        return self.code

    class Meta:
        verbose_name = _('color')
        verbose_name_plural = _('colors')


class SizeModel(models.Model):
    name = models.CharField(max_length=5, verbose_name=_('name'))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('created at'))

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('size')
        verbose_name_plural = _('sizes')


class BrandModel(models.Model):
    name = models.CharField(max_length=255, verbose_name=_('name'))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('created at'))

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('brand')
        verbose_name_plural = _('brands')


class TagModel(models.Model):
    name = models.CharField(max_length=54, verbose_name=_('name'))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('created at'))

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('tag')
        verbose_name_plural = _('tags')


class CategoryModel(models.Model):
    name = models.CharField(max_length=255, verbose_name=_('name'))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('created at'))

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('category')
        verbose_name_plural = _('categories')


class ProductModel(models.Model):
    name = models.CharField(max_length=255, verbose_name=_('name'))
    image = models.ImageField(upload_to='products', verbose_name=_('image'))
    price = models.FloatField(verbose_name=_('price'))
    real_price = models.FloatField(verbose_name=_('real price'), default=0)
    discount = models.PositiveIntegerField(default=0, verbose_name=_('discount'))
    short_description = models.TextField(verbose_name=_('short description'))
    long_description = models.TextField(verbose_name=_('long description'))
    category = models.ForeignKey(
        CategoryModel,
        on_delete=models.PROTECT,
        related_name='products',
        verbose_name=_('category')
    )
    brand = models.ForeignKey(
        BrandModel,
        on_delete=models.PROTECT,
        related_name='products',
        verbose_name=_('brand'),
        null=True,
        blank=True
    )
    color = models.ManyToManyField(
        ColorModel,
        related_name='products',
        verbose_name=_('color'),
        null=True,
        blank=True
    )
    size = models.ManyToManyField(
        SizeModel,
        related_name='products',
        verbose_name=_('size'),
        null=True,
        blank=True
    )
    tag = models.ManyToManyField(
        TagModel,
        related_name='products',
        verbose_name=_('tag')
    )
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('created at'))

    def is_new(self):
        return (timezone.now() - self.created_at).days <= 3

    def is_discount(self):
        return self.discount != 0

    def get_related(self):
        return ProductModel.objects.filter(category__name=self.category).exclude(pk=self.pk)[:4]

    @staticmethod
    def get_cart_info(cart):
        return ProductModel.objects.filter(id__in=cart)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('product')
        verbose_name_plural = _('products')


class ProductImageModel(models.Model):
    product = models.ForeignKey(
        ProductModel,
        on_delete=models.CASCADE,
        related_name='product_images'
    )
    image = models.ImageField(upload_to='product_image/')

    def __str__(self):
        return self.product.name

    class Meta:
        verbose_name = 'product image'
        verbose_name_plural = 'product images'

shop/forms.py
from django import forms
from .models import ColorModel


class ColorModelForm(forms.ModelForm):
    code = forms.CharField(max_length=7, widget=forms.TextInput(attrs={'type': 'color'}),)

    class Meta:
        model = ColorModel
        fields = '__all__'

shop/views.py
from django.db.models import Min, Max
from django.shortcuts import render
from django.views.generic import ListView, DetailView, TemplateView
from .models import *


class ShopView(ListView):
    model = ProductModel
    paginate_by = 3
    template_name = 'main/shop.html'

    def get_context_data(self, *args, object_list=None, **kwargs):
        context = super(ShopView, self, *args, **kwargs).get_context_data()
        context['categories'] = CategoryModel.objects.all()
        context['brands'] = BrandModel.objects.all()
        context['tags'] = TagModel.objects.all()
        context['sizes'] = SizeModel.objects.all()
        context['colors'] = ColorModel.objects.all()

        # select avg(salary) as sum_salary from emp

        # context['min_price'], context['max_price']

        context['min_price'], context['max_price'] = ProductModel.objects.aggregate(
            Min('real_price'),
            Max('real_price')
        ).values()



        return context

    def get_queryset(self):
        qs = ProductModel.objects.all()
        q = self.request.GET.get('q')
        if q:
            qs = qs.filter(name__icontains=q)
            return qs

        cat = self.request.GET.get('cat')
        if cat:
            qs = qs.filter(category_id=cat)


        brand = self.request.GET.get('brand')
        if brand:
            qs = qs.filter(brand_id=brand)

        tag = self.request.GET.get('tag')
        if tag:
            qs = qs.filter(tag__id=tag)

        size = self.request.GET.get('size')
        if size:
            qs = qs.filter(size__id=size)

        color = self.request.GET.get('color')
        if color:
            qs = qs.filter(color__id=color)

        price_sort = self.request.GET.get('price_sort')
        if price_sort == 'price':
            qs = qs.order_by('real_price')
        elif price_sort == '-price':
            qs = qs.order_by('-real_price')

        price = self.request.GET.get('price')
        if price:
            min, max = price.split(';')
            qs = qs.filter(real_price__gte=min, real_price__lte=max)

        return qs


class ProductDetailView(DetailView):
    model = ProductModel
    template_name = 'main/product_detail.html'

templates/main/blog_detail.html
{% extends 'base.html' %}

{% block content %}
    <section class="blog-hero spad">
        <div class="container">
            <div class="row d-flex justify-content-center">
                <div class="col-lg-9 text-center">
                    <div class="blog__hero__text">
                        <h2>{{ post.title }}</h2>
                        <ul>
                            <li>By {{ post.author }}</li>
                            <li>{{ post.created_at|date:'F d, Y' }}</li>
                            <li>{{ post.comments.all.count }} Comments</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="blog-details spad">
        <div class="container">
            <div class="row d-flex justify-content-center">
                <div class="col-lg-12">
                    <div class="blog__details__pic">
                        <img src="{{ post.banner.url }}" alt="{{ post.title }}">
                    </div>
                </div>
                <div class="col-lg-8">
                    <div class="blog__details__content">
                        <div class="blog__details__share">
                            <span>share</span>
                            <ul>
                                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                <li><a href="#" class="twitter"><i class="fa fa-twitter"></i></a></li>
                                <li><a href="#" class="youtube"><i class="fa fa-youtube-play"></i></a></li>
                                <li><a href="#" class="linkedin"><i class="fa fa-linkedin"></i></a></li>
                            </ul>
                        </div>
                        <div class="blog__details__text">
                            <p>
                                {{ post.description }}
                            </p>
                        </div>
                        <div class="blog__details__quote">
                            <i class="fa fa-quote-left"></i>
                            <p>“When designing an advertisement for a particular product many things should be
                                researched like where it should be displayed.”</p>
                            <h6>_ John Smith _</h6>
                        </div>
                        <div class="blog__details__text">
                            <p>Vyo-Serum along with tightening the skin also reduces the fine lines indicating aging of
                                skin. Problems like dark circles, puffiness, and crow’s feet can be control from the
                                strong effects of this serum.</p>
                            <p>Hydroderm is a multi-functional product that helps in reducing the cellulite and giving
                                the body a toned shape, also helps in cleansing the skin from the root and not letting
                                the pores clog, nevertheless also let’s sweeps out the wrinkles and all signs of aging
                                from the sensitive near the eyes.</p>
                        </div>
                        <div class="blog__details__option">
                            <div class="row">
                                <div class="col-lg-6 col-md-6 col-sm-6">
                                    <div class="blog__details__author">
                                        <div class="blog__details__author__pic">
                                            <img src="{{ post.author.avatar.url }}" alt="">
                                        </div>
                                        <div class="blog__details__author__text">
                                            <h5>{{ post.author }}</h5>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-6 col-md-6 col-sm-6">
                                    <div class="blog__details__tags">
                                        {% for tag in post.tags.all %}
                                            <a href="{% url 'blogs:blog_list' %}?tag={{ tag }}">#{{ tag }}</a>
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="blog__details__btns">
                            <div class="row">
                                <div class="col-lg-6 col-md-6 col-sm-6">
                                    {% if post.get_previous_by_created_at %}
                                        <a href="{% url 'blogs:blog_detail' pk=post.get_previous_by_created_at.id %}"
                                           class="blog__details__btns__item">
                                            <p><span class="arrow_left"></span> Previous Pod</p>
                                            <h5>{{ post.get_previous_by_created_at.title }}</h5>
                                        </a>
                                    {% endif %}
                                </div>
                                <div class="col-lg-6 col-md-6 col-sm-6">
                                    {% if post.get_next_by_created_at %}
                                        <a href="{% url 'blogs:blog_detail' pk=post.get_next_by_created_at.id %}"
                                           class="blog__details__btns__item blog__details__btns__item--next">
                                            <p>Next Pod <span class="arrow_right"></span></p>
                                            <h5>{{ post.get_next_by_created_at.title }}</h5>
                                        </a>
                                    {% endif %}
                                </div>
                            </div>
                        </div>

                        <div class="container py-3">
                            {% for comment in post.comments.all %}
                            <div class="row">
                                <div class="col-6 mb-3">
                                    <strong>{{ comment.name }}</strong>
                                </div>
                                <div class="col-6 mb-3 text-right">
                                    {{ comment.created_at|timesince }}
                                </div>
                                <div class="col-12 mb-3">
                                    <p>
                                        {{ comment.comment }}
                                    </p>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                        <div class="blog__details__comment">
                            <h4>Leave A Comment</h4>
                            <form action="{% url 'blogs:blog_comment' pk=post.id %}" method="POST">
                                {% csrf_token %}
                                <div class="row">
                                        <div class="col-lg-4 col-md-4">
                                            <input name="name" type="text" placeholder="Name">
                                        </div>
                                        <div class="col-lg-4 col-md-4">
                                            <input name="email" type="text" placeholder="Email">
                                        </div>
                                        <div class="col-lg-4 col-md-4">
                                            <input name="phone" type="text" placeholder="Phone">
                                        </div>
                                        <div class="col-lg-12 text-center">
                                            <textarea name="comment" placeholder="Comment"></textarea>
                                            <button type="submit" class="site-btn">Post Comment</button>
                                        </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/main/blog_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <section class="breadcrumb-blog set-bg" data-setbg="{% static 'img/breadcrumb-bg.jpg' %}">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h2>
                        {% if request.GET.tag %}
                            #{{ request.GET.tag }}
                        {% else %}
                            Our Blog
                        {% endif %}

                    </h2>
                </div>
            </div>
        </div>
    </section>

    <section class="blog spad">
        <div class="container">
            <div class="row">
                {% for post in posts %}
                    <div class="col-lg-4 col-md-6 col-sm-6">
                        <div class="blog__item">
                            <div class="blog__item__pic set-bg" data-setbg="{{ post.main_image.url }}"></div>
                            <div class="blog__item__text">
                                <span><img src="{% static 'img/icon/calendar.png' %}"
                                           alt="">{{ post.created_at|date:'d F Y' }}</span>
                                <h5>{{ post.title|slice:'50' }}</h5>
                                <a href="{% url 'blogs:blog_detail' post.pk %}">Read More</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}

            </div>
        </div>
    </section>
    {% if page_obj.paginator.count > 6 %}
    <section class="container mb-4 pb-5">
        <div class="row">
            <div class="col-lg-12">
                <div class="product__pagination">
                    {% for page in page_obj.paginator.page_range %}
                        <a {% if page == page_obj.number %}class="active"{% endif %} href="?page={{ page }}">
                            {{ page }}
                        </a>
                    {% endfor %}
                </div>
            </div>
        </div>
    </section>
    {% endif %}
{% endblock %}

templates/main/checkout.html
{% extends "base.html" %}
{% load my_tags %}
{% block content %}
    <section class="breadcrumb-option">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb__text">
                        <h4>Check Out</h4>
                        <div class="breadcrumb__links">
                            <a href="{% url 'pages:home' %}">Home</a>
                            <a href="{% url 'shops:shop' %}">Shop</a>
                            <span>Check Out</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="checkout spad">
        <div class="container">
            <div class="checkout__form">
                <form action="#" method="post">
                    {% csrf_token %}
                <p>
                    {{ form.errors }}
                </p>
                    <div class="row">
                        <div class="col-lg-8 col-md-6">
                            <h6 class="coupon__code"><span class="icon_tag_alt"></span> Have a coupon? <a href="#">Click
                                here</a> to enter your code</h6>
                            <h6 class="checkout__title">Billing Details</h6>
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="checkout__input">
                                        <p>First Name<span>*</span></p>
                                        <input type="text" value="{{ profile.first_name|default:'' }}"
                                               name="first_name">
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="checkout__input">
                                        <p>Last Name<span>*</span></p>
                                        <input type="text" value="{{ profile.last_name|default:'' }}" name="last_name">
                                    </div>
                                </div>
                            </div>
                            <div class="checkout__input">
                                <p>Country<span>*</span></p>
                                <input type="text" value="{{ profile.country|default:'' }}" name="country">
                            </div>
                            <div class="checkout__input">
                                <p>Address<span>*</span></p>
                                <input type="text" value="{{ profile.address1|default:'' }}" name="address1"
                                       placeholder="Street Address" class="checkout__input__add">
                                <input type="text" value="{{ profile.address2|default:'' }}" name="address2"
                                       placeholder="Apartment, suite, unite ect (optinal)">
                            </div>
                            <div class="checkout__input">
                                <p>Town/City<span>*</span></p>
                                <input type="text" value="{{ profile.city|default:'' }}" name="city">
                            </div>
                            <div class="checkout__input">
                                <p>Country/State<span>*</span></p>
                                <input type="text" value="{{ profile.state|default:'' }}" name="state">
                            </div>
                            <div class="checkout__input">
                                <p>Postcode / ZIP<span>*</span></p>
                                <input type="text" value="{{ profile.zip_code|default:'' }}" name="zip_code">
                            </div>
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="checkout__input">
                                        <p>Phone<span>*</span></p>
                                        <input type="text" value="{{ profile.phone|default:'' }}" name="phone">
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="checkout__input">
                                        <p>Email<span>*</span></p>
                                        <input type="text" value="{{ profile.email|default:'' }}" name="email">
                                    </div>
                                </div>
                            </div>

                        </div>
                        <div class="col-lg-4 col-md-6">
                            <div class="checkout__order">
                                <h4 class="order__title">Your order</h4>
                                <div class="checkout__order__products">Product <span>Total</span></div>
                                <ul class="checkout__total__products">
                                    {% for product in products %}
                                        <li>{{ forloop.counter }}. {{ product.name }}
                                            <span>$ {{ product.real_price }}</span></li>
                                    {% endfor %}
                                </ul>
                                <ul class="checkout__total__all">
                                    {% get_cart_info request as cart_info %}
                                    <li>Total <span>$ {{ cart_info.1 }}</span></li>
                                </ul>
                                <div class="checkout__input__checkbox">
                                    <label for="acc-or">
                                        Create an account?
                                        <input type="checkbox" id="acc-or">
                                        <span class="checkmark"></span>
                                    </label>
                                </div>
                                <p>Lorem ipsum dolor sit amet, consectetur adip elit, sed do eiusmod tempor incididunt
                                    ut labore et dolore magna aliqua.</p>
                                <div class="checkout__input__checkbox">
                                    <label for="payment">
                                        Check Payment
                                        <input type="checkbox" id="payment">
                                        <span class="checkmark"></span>
                                    </label>
                                </div>
                                <div class="checkout__input__checkbox">
                                    <label for="paypal">
                                        Paypal
                                        <input type="checkbox" id="paypal">
                                        <span class="checkmark"></span>
                                    </label>
                                </div>
                                <button type="submit" class="site-btn">PLACE ORDER</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </section>
{% endblock %}

templates/main/shopping_cart.html
{% extends 'base.html' %}
{% load static %}
{% load my_tags %}
{% block content %}

    <section class="breadcrumb-option">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb__text">
                        <h4>Shopping Cart</h4>
                        <div class="breadcrumb__links">
                            <a href="{% url 'pages:home' %}">Home</a>
                            <a href="{% url 'shops:shop' %}">Shop</a>
                            <span>Shopping Cart</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="shopping-cart spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="shopping__cart__table">
                        <table>
                            <thead>
                            <tr>
                                <th>Product</th>
                                <th>Quantity</th>
                                <th>Total</th>
                                <th></th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for product in object_list %}
                            <tr>
                                <td class="product__cart__item">
                                    <div class="product__cart__item__pic">
                                        <img src="{{ product.image.url }}" alt="{{ product.name }}">
                                    </div>
                                    <div class="product__cart__item__text">
                                        <h6>{{ product.name }}</h6>
                                        <h5>${{ product.real_price }}</h5>
                                    </div>
                                </td>
                                <td class="quantity__item">
                                    <div class="quantity">
                                        <div class="pro-qty-2">
                                            <input type="text" value="1">
                                        </div>
                                    </div>
                                </td>
                                <td class="cart__price">$ {{ product.real_price }}</td>
                                <td class="cart__close">
                                    <a href="{% url 'products:add_cart' product.id %}?next={{ request.path }}">
                                        <i class="fa fa-close"></i>
                                    </a>
                                </td>
                            </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    <div class="row">
                        <div class="col-lg-6 col-md-6 col-sm-6">
                            <div class="continue__btn">
                                <a href="#">Continue Shopping</a>
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-6">
                            <div class="continue__btn update__btn">
                                <a href="#"><i class="fa fa-spinner"></i> Update cart</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="cart__discount">
                        <h6>Discount codes</h6>
                        <form action="#">
                            <input type="text" placeholder="Coupon code">
                            <button type="submit">Apply</button>
                        </form>
                    </div>
                    <div class="cart__total">
                        <h6>Cart total</h6>
                        <ul>
                            {% get_cart_info request as cart_info %}
                            <li>Total <span>$ {{ cart_info.1 }}</span></li>
                        </ul>
                        <a href="{% url 'orders:checkout' %}" class="primary-btn">Proceed to checkout</a>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}