auth/urls.py
from django.urls import path, include
from .views import reset_password
urlpatterns = [
    path('password/change/done/', reset_password),
    path('', include('registration.backends.default.urls'))
]

blog/urls.py
from django.urls import path
from .views import BlogListView, BlogDetailView, BlogCommentView

app_name = 'blogs'

urlpatterns = [
    path('<int:pk>/comment/', BlogCommentView.as_view(), name='blog_comment'),
    path('<int:pk>/post/', BlogDetailView.as_view(), name='blog_detail'),
    path('', BlogListView.as_view(), name='blog_list')
]

config/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

]

urlpatterns += i18n_patterns(
    path('accounts/', include('auth.urls')),
    path('admin/', admin.site.urls),
    path('order/', include('orders.urls', namespace='orders')),
    path('profile/', include('client.urls', namespace='profile')),
    path('product/', include('product.urls', namespace='products')),
    path('shop/', include('shop.urls', namespace='shops')),
    path('blog/', include('blog.urls', namespace='blogs')),
    path('', include('pages.urls', namespace='pages'))
)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path

from orders.views import CheckoutView, OrderHistoryListView

app_name = 'orders'

urlpatterns = [
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('history/', OrderHistoryListView.as_view(), name='history')
]

pages/urls.py
from django.urls import path
from .views import HomePageView, ContactView, AboutView

app_name = 'pages'

urlpatterns = [
    path('about/', AboutView.as_view(), name='about'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('', HomePageView.as_view(), name='home')
]

shop/urls.py
from django.urls import path
from .views import ShopView, ProductDetailView

app_name = 'shops'

urlpatterns = [
    path('', ShopView.as_view(), name='shop'),
    path('<int:pk>/detail/', ProductDetailView.as_view(), name='product_detail'),
]

templates/layouts/navbar.html
{% load static %}
{% load my_tags %}
{% load i18n %}
<!-- Header Section Begin -->
<header class="header">
    <div class="header__top">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 col-md-7">
                    <div class="header__top__left">
                        <p>{% trans 'Free shipping, 30-day return or refund guarantee.' %}</p>
                    </div>
                </div>
                <div class="col-lg-6 col-md-5">
                    <div class="header__top__right">
                        <div class="header__top__links">
                            {% if request.user.is_authenticated %}
                                <a href="{% url 'orders:history' %}">{% trans 'History' %}</a>
                                <a href="{% url 'profile:home' %}">{% trans 'Profile' %}</a>
                                <a href="{% url 'auth_logout' %}">{% trans 'Log out' %}</a>
                            {% else %}
                                <a href="{% url 'auth_login' %}">{% trans 'Sign in' %}</a>
                            {% endif %}


                        </div>
                        <div class="header__top__hover">
                            {% get_current_language as current_lan %}

                            <span>{{ current_lan }} <i class="arrow_carrot-down"></i></span>
                            <ul>
                                {% get_available_languages as languages %}
                                {% for lan in languages %}
                                    {% if lan.0 != current_lan %}
                                        <li>
                                            <a href="/{{ lan.0 }}/{{ request.path|slice:'4:' }}"
                                               style="text-decoration: none; color: black;">{{ lan.0|upper }}</a>
                                        </li>
                                    {% endif %}
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-3">
                <div class="header__logo">
                    <a href="{% url 'pages:home' %}"><img src="{% static 'img/logo.png' %}" alt=""></a>
                </div>
            </div>
            <div class="col-lg-6 col-md-6">
                <nav class="header__menu mobile-menu">
                    <ul>
                        {% url 'pages:home' as current_path %}
                        <li {% if request.path == current_path %}class="active"{% endif %}>
                            <a href="{% url 'pages:home' %}">{% trans 'Home' %}</a>
                        </li>
                        {% url 'shops:shop' as current_path %}
                        <li {% if request.path == current_path %}class="active"{% endif %}>
                            <a href="{% url 'shops:shop' %}">{% trans 'Shop' %}</a>
                        </li>
                        {% url 'blogs:blog_list' as current_path %}
                        <li {% if request.path == current_path %}class="active"{% endif %}>
                            <a href="{% url 'blogs:blog_list' %}">{% trans 'Blog' %}</a>
                        </li>
                        {% url 'pages:about' as current_path %}
                        <li {% if request.path == current_path %}class="active"{% endif %}>
                            <a href="{% url 'pages:about' %}">{% trans 'About Us' %}</a>
                        </li>
                        {% url 'pages:contact' as current_path %}
                        <li {% if request.path == current_path %}class="active"{% endif %}>
                            <a href="{% url 'pages:contact' %}">{% trans 'Contacts' %}</a>
                        </li>
                    </ul>
                </nav>
            </div>
            <div class="col-lg-3 col-md-3">
                <div class="header__nav__option">
                    <a href="#" class="search-switch"><img src="{% static 'img/icon/search.png' %}" alt=""></a>
                    {% if request.user.is_authenticated %}
                        <a href="{% url 'products:wishlist' %}">
                            <img src="{% static 'img/icon/heart.png' %}" alt="">
                        </a>
                    {% endif %}
                    {% get_cart_info request as cart_info %}
                    <a href="{% url 'products:shopping_cart' %}"><img src="{% static 'img/icon/cart.png' %}" alt="">
                        <span>{{ cart_info.0 }}</span></a>
                    <div class="price">${{ cart_info.1 }}</div>

                </div>
            </div>
        </div>
        <div class="canvas__open"><i class="fa fa-bars"></i></div>
    </div>
</header>

templates/layouts/shop_sidebar.html
<div class="shop__sidebar__search">
    <form action="{% url 'shops:shop' %}">
        <input value="{{ request.GET.q }}" name="q" type="text" placeholder="Search...">
        <button type="submit"><span class="icon_search"></span></button>
    </form>
</div>
<div class="shop__sidebar__accordion">
    <div class="accordion" id="accordionExample">
    <div class="card">
            <div class="card-heading">
                <a data-toggle="collapse" data-target="#collapseThree">Filter Price</a>
            </div>
            <div id="collapseThree" class="collapse show" data-parent="#accordionExample">
                <div class="card-body">
                    <div class="shop__sidebar__price">
                         <input type="text" class="js-range-slider" name="my_range" value="" />
                    </div>
                </div>
            </div>
        </div>
        <div class="card">
            <div class="card-heading">
                <a data-toggle="collapse" data-target="#collapseOne">Categories</a>
            </div>
            <div id="collapseOne" class="collapse show" data-parent="#accordionExample">
                <div class="card-body">
                    <div class="shop__sidebar__categories">
                        <ul class="nice-scroll">
                            {% for category in categories %}
                                <li><a {% if request.GET.cat == category.pk|stringformat:'i' %} class="text-dark"{% endif %} onclick="getParamSearch('cat', {{ category.pk }})">{{ category }}</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="card">
            <div class="card-heading">
                <a data-toggle="collapse" data-target="#collapseTwo">Branding</a>
            </div>
            <div id="collapseTwo" class="collapse show" data-parent="#accordionExample">
                <div class="card-body">
                    <div class="shop__sidebar__brand">
                        <ul>
                            {% for b in brands %}
                                <li><a {% if request.GET.brand == b.pk|stringformat:'i' %} class="text-dark"{% endif %} onclick="getParamSearch('brand', {{ b.pk }})">{{ b }}</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="card">
            <div class="card-heading">
                <a data-toggle="collapse" data-target="#collapseFour">Size</a>
            </div>
            <div id="collapseFour" class="collapse show" data-parent="#accordionExample">
                <div class="card-body">
                    <div class="shop__sidebar__size">
                        {% for size in sizes %}
                                <a {% if request.GET.size == size.pk|stringformat:'i' %}class="active"{% endif %} onclick="getParamSearch('size', {{ size.pk }})">{{ size }}</a>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
        <div class="card">
            <div class="card-heading">
                <a data-toggle="collapse" data-target="#collapseFive">Colors</a>
            </div>
            <div id="collapseFive" class="collapse show" data-parent="#accordionExample">
                <div class="card-body">
                    <div class="shop__sidebar__color">
                        {% for color in colors %}
                             <a
                                style="background: {{ color }}"
                                onclick="getParamSearch('color', {{ color.pk }})"
                             >
                             </a>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
        <div class="card">
            <div class="card-heading">
                <a data-toggle="collapse" data-target="#collapseSix">Tags</a>
            </div>
            <div id="collapseSix" class="collapse show" data-parent="#accordionExample">
                <div class="card-body">
                    <div class="shop__sidebar__tags">
                        {% for tag in tags %}
                            <a
                                    {% if request.GET.tag == tag.pk|stringformat:'i' %}class="active" {% endif %}
                                    onclick="getParamSearch('tag', {{ tag.pk }})"
                            >
                                {{ tag }}
                            </a>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>